### ISSUE TITLE
Account for unicode in meta strings and path names

### ISSUE THREAD

**Issue by tasket** [tasket/wyng-backup#190]
### Problem

Unicode is not fully handled.  This is because many local command invocations expect the 'C' locale for efficiency (and this was the only locale necessary for local cmds when Wyng was limited to LVM).  Support for reflink volumes makes explicit unicode support necessary. Some of this unicode impacts metadata max size estimates in ArchiveSet objects.

* Some parts of Wyng might not find non-ASCII unicode paths (reflink mode).
* Max size estimates need adjustment.

### Solution

- [x] Keep the 'LC_ALL=C' locale default, but unset it for specific commands that handle user-supplied paths. For example, the `cp --reflink` command and various `btrfs subvolume` commands that will have to operate on user volume names and paths, not just Wyng-generated snapshot paths.
- [x] For remote commands, use a _destcd_ parameter so that archive root may be cd'd to before 'LC_ALL=C' is set.
- [x] Multiply specific fields in Archive* classes by 4 to cover unicode expansion.

### Related

Issue #75

**Comment by tasket** [comment]
Implementation will perform destination `cd` before 'LC_ALL' is set.  This allows cd-ing to the archive using the default locale; a subsequent `cd` may then be issued (after locale is set) in the command list if descending further into archive is necessary.
